SELECT  JR023EMP, JR023USU, JR023SUC, JR023EJE, 
        JR023CARCL, JR023CARCR, JR023CARVL, 
        JR023CRECL, JR023CRECR, JR023CREVL, 
        JR023MOMEP, JR023MOMEV, JR023MOMAP, 
        JR023MOMAV, JR023MOTOP, JR023MOTOV, 
        JR023DEMEP, JR023DEMEV, JR023DEMAP, 
        JR023DEMAV, JR023DETOP, JR023DETOV, 
        JR023COLCR, JR023COLVL, 
        JR023PENCR, JR023PENVL, 
        HORA, FECHA,TRUNC(FECHA) AS FECHA_
FROM I_BMIA.STG_JBMYR023 WHERE HORA = (
               SELECT MIN(HORA)  /*MINIMA HORA*/
                      FROM I_BMIA.STG_JBMYR023 
               WHERE TRUNC(FECHA) IN (SELECT TRUNC(FEC_HOMLGD_MAYOR) FROM I_BMIA.APX_REPONLINE_PARAM WHERE TRUNC(FEC_ACT) = TRUNC(CURRENT_DATE))
            ) 
AND TRUNC(FECHA) IN (SELECT TRUNC(FEC_HOMLGD_MAYOR) FROM I_BMIA.APX_REPONLINE_PARAM WHERE TRUNC(FEC_ACT) = TRUNC(CURRENT_DATE));